os.execute('rd /s/q "'.."core/single/"..'"')
os.execute('rd /s/q "'.."core/client/"..'"')
os.execute('rd /s/q "'.."core/udp/"..'"')
os.execute('rd /s/q "'.."scripts/lang/"..'"')
os.execute('rd /s/q "'.."scripts/sarah/"..'"')
os.execute('rd /s/q "'.."scripts/utils/pretty/"..'"')
os.remove("scripts/check_click.lua")
os.remove("scripts/check_click_custom_map.lua")
os.remove("scripts/on_key.lua")
os.remove("scripts/save_system.lua")
os.remove("scripts/settings.lua")
os.remove("scripts/utils/random_name.lua")