--p - population
--o - own
--a - army
local game_data = {
	id = "consequences",
	map = "europe",
	name = "Современный мир(2019)",
	temperature_rise = 0,
	year = 2020,
	technology_lvl = 16,
	player_land = "England",
	lands = {
		England = {
			name = "great_britain",
			banner = "union_jack",
			color = {103, 158, 124},
			capital = "london"
		},
		Iceland = {
			name = "iceland",
			banner = "iceland",
			color = {108, 134, 158},
			capital = "iceland"
		},
		Ireland = {
			name = "ireland",
			banner = "ireland",
			color = {215, 170, 159},
			capital = "middle_ireland"
		},
		Spain = {
			name = "spain",
			banner = "spain",
			color = {209, 207, 102},
			capital = "madrid"
		},
		Portugal = {
			name = "portugal",
			banner = "portugal",
			color = {126, 158, 108},
			capital = "lisboa"
		},
		Italy = {
			name = "italy",
			banner = "italy",
			color = {168, 159, 215},
			capital = "roma",
		},
		Switzerland = {
			name = "switzerland",
			banner = "switzerland",
			color = {95, 107, 105},
			capital = "schweiz",
		},
		France = {
			name = "france",
			banner = "france_1976",
			color = {214, 195, 109},
			capital = "paris",
		},
		Belgium = {
			name = "belgium",
			banner = "belgium",
			color = {158, 116, 103},
			capital = "belgium",
		},
		Netherlands = {
			name = "netherlands",
			banner = "netherlands",
			color = {103, 108, 158},
			capital = "nederland",
		},
		Germany = {
			name = "germany",
			banner = "germany",
			color = {96, 166, 209},
			capital = "berlin"
		},
		Luxembourg = {
			name = "luxembourg",
			banner = "luxembourg",
			color = {120, 153, 82},
			capital = "luxembourg"
		},
		Austria = {
			name = "austria",
			banner = "austria",
			color = {83, 123, 153},
			capital = "wien"
		},
		Czechia = {
			name = "czechia",
			banner = "czech",
			color = {83, 138, 153},
			capital = "praha"
		},
		Slovenia = {
			name = "slovenia",
			banner = "slovenia",
			color = {153, 120, 83},
			capital = "slovenija"
		},
		Croatia = {
			name = "croatia",
			banner = "croatia",
			color = {153, 153, 98},
			capital = "zagreb"
		},
		Bosnia_and_herzegovina = {
			name = "bosnia_and_herzegovina",
			banner = "bosnia_and_herzegovina",
			color = {158, 129, 131},
			capital = "bosna_i_hercegovina"
		},
		Montenegro = {
			name = "montenegro",
			banner = "montenegro_2004",
			color = {98, 153, 111},
			capital = "crna_gora"
		},
		Albania = {
			name = "albania",
			banner = "albania",
			color = {100, 83, 153},
			capital = "albania"
		},
		Serbia = {
			name = "serbia",
			banner = "serbia",
			color = {128, 127, 87},
			capital = "beograd"
		},
		Macedonia = {
			name = "macedonia",
			banner = "macedonia",
			color = {128, 118, 81},
			capital = "macedonia"
		},
		Greece = {
			name = "greece",
			banner = "greece",
			color = {47, 100, 128},
			capital = "athens"
		},
		Turkey = {
			name = "turkey",
			banner = "turkey",
			color = {73, 78, 128},
			capital = "ankara"
		},
		Cyprus = {
			name = "cyprus",
			banner = "cyprus",
			color = {75, 128, 93},
			capital = "cyprus"
		},
		Hungary = {
			name = "hungary",
			banner = "hungary",
			color = {125, 128, 55},
			capital = "budapest"
		},
		Slovakia = {
			name = "slovakia",
			banner = "slovakia",
			color = {108, 72, 128},
			capital = "bratislava"
		},
		Romania = {
			name = "romania",
			banner = "romania",
			color = {128, 65, 87},
			capital = "bucuresti"
		},
		Moldavia = {
			name = "moldavia",
			banner = "moldavia",
			color = {102, 133, 125},
			capital = "moldova"
		},
		Ukraine = {
			name = "ukraine",
			banner = "ukraine",
			color = {61, 111, 133},
			capital = "kiev"
		},
		Poland = {
			name = "poland",
			banner = "poland",
			color = {67, 79, 133},
			capital = "warszawa"
		},
		Lithuania = {
			name = "lithuania",
			banner = "lithuania",
			color = {133, 102, 115},
			capital = "vilnius"
		},
		Latvia = {
			name = "latvia",
			banner = "latvia",
			color = {118, 133, 54},
			capital = "riga"
		},
		Estonia = {
			name = "estonia",
			banner = "estonia",
			color = {44, 48, 133},
			capital = "eesti"
		},
		Belarus = {
			name = "belarus",
			banner = "belarus",
			color = {48, 133, 52},
			capital = "minsk"
		},
		Denmark = {
			name = "denmark",
			banner = "denmark",
			color = {133, 117, 102},
			capital = "denmark"
		},
		Sweden = {
			name = "sweden",
			banner = "sweden",
			color = {122, 107, 133},
			capital = "stockholm"
		},
		Norway = {
			name = "norway",
			banner = "norway",
			color = {133, 81, 52},
			capital = "oslo"
		},
		Finland = {
			name = "finland",
			banner = "finland",
			color = {102, 130, 133},
			capital = "helsinki"
		},
		Russia = {
			name = "russia",
			banner = "russia",
			color = {118, 133, 94},
			capital = "moscow"
		},
		Bulgaria = {
			name = "bulgaria",
			banner = "bulgaria",
			color = {133, 55, 0},
			capital = "sofia"
		},
		Undeveloped_land = {
			name = "undeveloped_land",
			color = {200,200,200},
		}
	},
	provinces = {
		akhisar= {o = "Turkey", tmp = 20},
		albania= {o = "Albania", tmp = 20},
		alesund= {o = "Norway", tmp = 5},
		alta= {o = "Norway", tmp = -10},
		ambrakia= {o = "Greece", tmp = 20},
		amiens= {o = "France", tmp = 15},
		ancona= {o = "Italy", tmp = 20},
		ankara= {o = "Turkey", tmp = 20},
		antalya= {o = "Turkey", tmp = 20},
		arkhangelsk= {o = "Russia", tmp = -10},
		athens= {o = "Greece", tmp = 20},
		badajoz= {o = "Spain", tmp = 30},
		barcelona= {o = "Spain", tmp = 20},
		belgium= {o = "Belgium", tmp = 15},
		beograd= {o = "Serbia", tmp = 20},
		bergen= {o = "Norway", tmp = 5},
		berlin= {o = "Germany", tmp = 15},
		besancon= {o = "France", tmp = 15},
		bialystok= {o = "Poland", tmp = 10},
		bilbo= {o = "Spain", tmp = 20},
		bologna= {o = "Italy", tmp = 20},
		bolu= {o = "Turkey", tmp = 15},
		bordeaux= {o = "France", tmp = 15},
		borlange= {o = "Sweden", tmp = 15},
		bosna_i_hercegovina= {o = "Bosnia_and_herzegovina", tmp = 15},
		bourges= {o = "France", tmp = 15},
		bratislava= {o = "Slovakia", tmp = 10},
		bremen= {o = "Germany", tmp = 15},
		brest= {o = "Belarus", tmp = 10},
		brno= {o = "Czechia", tmp = 10},
		bryansk= {o = "Russia", tmp = 10},
		bucuresti= {o = "Romania", tmp = 20},
		budapest= {o = "Hungary", tmp = 15},
		burgas= {o = "Bulgaria", tmp = 20},
		bursa= {o = "Turkey", tmp = 20},
		bydgoszcz= {o = "Poland", tmp = 15},
		caen= {o = "France", tmp = 15},
		calais= {o = "France", tmp = 15},
		cherkassy= {o = "Ukraine", tmp = 15},
		chernigov= {o = "Ukraine", tmp = 10},
		clermont_ferrand= {o = "France", tmp = 10},
		cluj_napoca= {o = "Romania", tmp = 10},
		coimbra= {o = "Portugal", tmp = 30},
		constanta= {o = "Romania", tmp = 20},
		corum= {o = "Turkey", tmp = 15},
		coruna= {o = "Spain", tmp = 20},
		cosenza= {o = "Italy", tmp = 20},
		crete= {o = "Greece", tmp = 20},
		crimea= {o = "Russia", tmp = 10},
		crna_gora= {o = "Montenegro", tmp = 15},
		cyprus= {o = "Cyprus", tmp = 20},
		daugavpils= {o = "Latvia", tmp = 10},
		denizli= {o = "Turkey", tmp = 20},
		denmark= {o = "Denmark", tmp = 15},
		dijon= {o = "France", tmp = 15},
		dnipro= {o = "Ukraine", tmp = 15},
		donetsk= {o = "Ukraine", tmp = 15},
		dortmund= {o = "Germany", tmp = 15},
		eesti= {o = "Estonia", tmp = 10},
		faro= {o = "Portugal", tmp = 30},
		firenze= {o = "Italy", tmp = 20},
		frankfurt_am_main= {o = "Germany", tmp = 15},
		gabrovo= {o = "Bulgaria", tmp = 20},
		gavle= {o = "Sweden", tmp = 15},
		gdynia= {o = "Poland", tmp = 10},
		gomel= {o = "Belarus", tmp = 10},
		goteborg= {o = "Sweden", tmp = 15},
		graz= {o = "Austria", tmp = 10},
		grodno= {o = "Belarus", tmp = 10},
		gyor= {o = "Hungary", tmp = 15},
		halmstad= {o = "Sweden", tmp = 15},
		hamar= {o = "Norway", tmp = 5},
		hamburg= {o = "Germany", tmp = 15},
		haskovo= {o = "Bulgaria", tmp = 20},
		helsinki= {o = "Finland", tmp = 5},
		iceland= {o = "Iceland", tmp = -15},
		innsbruck= {o = "Austria", tmp = 5},
		isparta= {o = "Turkey", tmp = 20},
		izmir= {o = "Turkey", tmp = 20},
		jonkoping= {o = "Sweden", tmp = 15},
		kalamata= {o = "Greece", tmp = 20},
		kaliningrad= {o = "Russia", tmp = 10},
		kalmar= {o = "Sweden", tmp = 15},
		kaluga= {o = "Russia", tmp = 10},
		karabuk= {o = "Turkey", tmp = 15},
		karaman= {o = "Turkey", tmp = 20},
		karelia= {o = "Russia", tmp = 0},
		karlstad= {o = "Sweden", tmp = 10},
		katrineholm= {o = "Sweden", tmp = 15},
		kharkiv= {o = "Ukraine", tmp = 15},
		kherson= {o = "Ukraine", tmp = 20},
		khmelnitsky= {o = "Ukraine", tmp = 20},
		kielce= {o = "Poland", tmp = 15},
		kiev= {o = "Ukraine", tmp = 15},
		kirov= {o = "Russia", tmp = 5},
		klaipeda= {o = "Lithuania", tmp = 10},
		komi= {o = "Russia", tmp = -15},
		konya= {o = "Turkey", tmp = 20},
		kosice= {o = "Slovakia", tmp = 15},
		kostroma= {o = "Russia", tmp = 0},
		kozan= {o = "Turkey", tmp = 20},
		krakow= {o = "Poland", tmp = 15},
		krasnodar= {o = "Russia", tmp = 20},
		kristiansand= {o = "Norway", tmp = 5},
		kuopio= {o = "Finland", tmp = 5},
		kursk= {o = "Russia", tmp = 10},
		la_rochelle= {o = "France", tmp = 15},
		lasi= {o = "Romania", tmp = 20},
		leeds= {o = "England", tmp = 15},
		limoges= {o = "France", tmp = 15},
		linkoping= {o = "Sweden", tmp = 15},
		lipetsk= {o = "Russia", tmp = 10},
		lisboa= {o = "Portugal", tmp = 30},
		london= {o = "England", tmp = 20},
		lublin= {o = "Poland", tmp = 15},
		lugansk= {o = "Ukraine", tmp = 15},
		lulea= {o = "Sweden", tmp = -5},
		lutsk= {o = "Ukraine", tmp = 15},
		luxembourg= {o = "Luxembourg", tmp = 15},
		lviv= {o = "Ukraine", tmp = 10},
		lyon= {o = "France", tmp = 10},
		macedonia= {o = "Macedonia", tmp = 20},
		madrid= {o = "Spain", tmp = 30},
		magdeburg= {o = "Germany", tmp = 15},
		malmo= {o = "Sweden", tmp = 15},
		marmaris= {o = "Turkey", tmp = 20},
		middle_ireland= {o = "Ireland", tmp = 20},
		milano= {o = "Italy", tmp = 15},
		minsk= {o = "Belarus", tmp = 10},
		mogilev= {o = "Belarus", tmp = 10},
		moldova= {o = "Moldavia", tmp = 15},
		montpellier= {o = "France", tmp = 10},
		moscow= {o = "Russia", tmp = 10},
		munchen= {o = "Germany", tmp = 15},
		murcia= {o = "Spain", tmp = 25},
		murmansk= {o = "Russia", tmp = -5},
		nancy= {o = "France", tmp = 15},
		nantes= {o = "France", tmp = 15},
		napoli= {o = "Italy", tmp = 25},
		nederland= {o = "Netherlands", tmp = 15},
		nenets= {o = "Russia", tmp = -10},
		nice= {o = "France", tmp = 15},
		nigde= {o = "Turkey", tmp = 20},
		nikolaev= {o = "Ukraine", tmp = 20},
		nis= {o = "Serbia", tmp = 20},
		nizhny_novgorod= {o = "Russia", tmp = 5},
		north_africa_1= {o = "Undeveloped_land", tmp = 20},
		north_africa_2= {o = "Undeveloped_land", tmp = 20},
		north_africa_3= {o = "Undeveloped_land", tmp = 20},
		northern_ireland= {o = "England", tmp = 20},
		nottingham= {o = "England", tmp = 20},
		novgorod= {o = "Russia", tmp = 10},
		odessa= {o = "Ukraine", tmp = 15},
		olsztyn= {o = "Poland", tmp = 10},
		orel= {o = "Russia", tmp = 10},
		oslo= {o = "Norway", tmp = 15},
		ostersund= {o = "Sweden", tmp = 5},
		otta= {o = "Norway", tmp = 5},
		oulu= {o = "Finland", tmp = 0},
		paris= {o = "France", tmp = 15},
		penza= {o = "Russia", tmp = 5},
		piter= {o = "Russia", tmp = 0},
		poltava= {o = "Ukraine", tmp = 15},
		porto= {o = "Portugal", tmp = 25},
		poznan= {o = "Poland", tmp = 15},
		praha= {o = "Czechia", tmp = 10},
		pskov= {o = "Russia", tmp = 10},
		reims= {o = "France", tmp = 15},
		rennes= {o = "France", tmp = 15},
		riga= {o = "Latvia", tmp = 10},
		roma= {o = "Italy", tmp = 20},
		rostov_on_don= {o = "Russia", tmp = 10},
		rouen= {o = "France", tmp = 15},
		rovaniemi= {o = "Finland", tmp = -10},
		ryazan= {o = "Russia", tmp = 10},
		samsun= {o = "Turkey", tmp = 20},
		saransk= {o = "Russia", tmp = 5},
		sardegna= {o = "Italy", tmp = 20},
		schweiz= {o = "Switzerland", tmp = 0},
		scotland= {o = "England", tmp = 15},
		sevilla= {o = "Spain", tmp = 30},
		sibiu= {o = "Romania", tmp = 10},
		sicilia= {o = "Italy", tmp = 20},
		sivas= {o = "Turkey", tmp = 20},
		slovenija= {o = "Slovenia", tmp = 15},
		smolensk= {o = "Russia", tmp = 10},
		sofia= {o = "Bulgaria", tmp = 20},
		southern_ireland= {o = "Ireland", tmp = 20},
		stockholm= {o = "Sweden", tmp = 15},
		strasbourg= {o = "France", tmp = 15},
		stuttgart= {o = "Germany", tmp = 15},
		sumy= {o = "Ukraine", tmp = 10},
		sundsvall= {o = "Sweden", tmp = 15},
		szczecin= {o = "Poland", tmp = 15},
		szeged= {o = "Hungary", tmp = 15},
		tambov= {o = "Russia", tmp = 10},
		tampere= {o = "Finland", tmp = 15},
		tekirdag= {o = "Turkey", tmp = 20},
		ternopol= {o = "Ukraine", tmp = 10},
		thessaloniki= {o = "Greece", tmp = 20},
		timisoara= {o = "Romania", tmp = 10},
		torino= {o = "Italy", tmp = 15},
		toulouse= {o = "France", tmp = 15},
		trier= {o = "Germany", tmp = 15},
		trofors= {o = "Norway", tmp = 0},
		tromso= {o = "Norway", tmp = -10},
		trondheim= {o = "Norway", tmp = 15},
		tula= {o = "Russia", tmp = 10},
		tver= {o = "Russia", tmp = 10},
		umea= {o = "Sweden", tmp = 5},
		uzice= {o = "Serbia", tmp = 20},
		valencia= {o = "Spain", tmp = 25},
		valladolid= {o = "Spain", tmp = 25},
		varna= {o = "Bulgaria", tmp = 20},
		vaxjo= {o = "Sweden", tmp = 15},
		venezia= {o = "Italy", tmp = 15},
		vilnius= {o = "Lithuania", tmp = 10},
		vitebsk= {o = "Belarus", tmp = 10},
		vladimir= {o = "Russia", tmp = 5},
		volgograd= {o = "Russia", tmp = 10},
		vologda= {o = "Russia", tmp = 0},
		voronezh= {o = "Russia", tmp = 10},
		vratsa= {o = "Bulgaria", tmp = 25},
		wales= {o = "England", tmp = 15},
		warszawa= {o = "Poland", tmp = 10},
		wien= {o = "Austria", tmp = 10},
		wroclaw= {o = "Poland", tmp = 15},
		yaroslavl= {o = "Russia", tmp = 5},
		zadar= {o = "Croatia", tmp = 15},
		zagreb= {o = "Croatia", tmp = 15},
		zaporozhye= {o = "Ukraine", tmp = 20},
		zaragoza= {o = "Spain", tmp = 25},
		zhitomir= {o = "Ukraine", tmp = 15},
		cheboksary= {o = "Russia", tmp = 5},
	}
}
return game_data