--p - population
--o - own
--a - army
local game_data = {
	id = "modern_world",
	map = "europe",
	name = "Современный мир(2019)",
	year = 2020,
	technology_lvl = 16,
	player_land = "England",
	lands = {
		England = {
			name = "great_britain",
			banner = "union_jack",
			color = {103, 158, 124},
			capital = "london"
		},
		Iceland = {
			name = "iceland",
			banner = "iceland",
			color = {108, 134, 158},
			capital = "iceland"
		},
		Ireland = {
			name = "ireland",
			banner = "ireland",
			color = {215, 170, 159},
			capital = "middle_ireland"
		},
		Spain = {
			name = "spain",
			banner = "spain",
			color = {209, 207, 102},
			capital = "madrid"
		},
		Portugal = {
			name = "portugal",
			banner = "portugal",
			color = {126, 158, 108},
			capital = "lisboa"
		},
		Italy = {
			name = "italy",
			banner = "italy",
			color = {168, 159, 215},
			capital = "roma",
		},
		Switzerland = {
			name = "switzerland",
			banner = "switzerland",
			color = {95, 107, 105},
			capital = "schweiz",
		},
		France = {
			name = "france",
			banner = "france_1976",
			color = {214, 195, 109},
			capital = "paris",
		},
		Belgium = {
			name = "belgium",
			banner = "belgium",
			color = {158, 116, 103},
			capital = "belgium",
		},
		Netherlands = {
			name = "netherlands",
			banner = "netherlands",
			color = {103, 108, 158},
			capital = "nederland",
		},
		Germany = {
			name = "germany",
			banner = "germany",
			color = {96, 166, 209},
			capital = "berlin"
		},
		Luxembourg = {
			name = "luxembourg",
			banner = "luxembourg",
			color = {120, 153, 82},
			capital = "luxembourg"
		},
		Austria = {
			name = "austria",
			banner = "austria",
			color = {83, 123, 153},
			capital = "wien"
		},
		Czechia = {
			name = "czechia",
			banner = "czech",
			color = {83, 138, 153},
			capital = "praha"
		},
		Slovenia = {
			name = "slovenia",
			banner = "slovenia",
			color = {153, 120, 83},
			capital = "slovenija"
		},
		Croatia = {
			name = "croatia",
			banner = "croatia",
			color = {153, 153, 98},
			capital = "zagreb"
		},
		Bosnia_and_herzegovina = {
			name = "bosnia_and_herzegovina",
			banner = "bosnia_and_herzegovina",
			color = {158, 129, 131},
			capital = "bosna_i_hercegovina"
		},
		Montenegro = {
			name = "montenegro",
			banner = "montenegro_2004",
			color = {98, 153, 111},
			capital = "crna_gora"
		},
		Albania = {
			name = "albania",
			banner = "albania",
			color = {100, 83, 153},
			capital = "albania"
		},
		Serbia = {
			name = "serbia",
			banner = "serbia",
			color = {128, 127, 87},
			capital = "beograd"
		},
		Macedonia = {
			name = "macedonia",
			banner = "macedonia",
			color = {128, 118, 81},
			capital = "macedonia"
		},
		Greece = {
			name = "greece",
			banner = "greece",
			color = {47, 100, 128},
			capital = "athens"
		},
		Turkey = {
			name = "turkey",
			banner = "turkey",
			color = {73, 78, 128},
			capital = "ankara"
		},
		Cyprus = {
			name = "cyprus",
			banner = "cyprus",
			color = {75, 128, 93},
			capital = "cyprus"
		},
		Hungary = {
			name = "hungary",
			banner = "hungary",
			color = {125, 128, 55},
			capital = "budapest"
		},
		Slovakia = {
			name = "slovakia",
			banner = "slovakia",
			color = {108, 72, 128},
			capital = "bratislava"
		},
		Romania = {
			name = "romania",
			banner = "romania",
			color = {128, 65, 87},
			capital = "bucuresti"
		},
		Moldavia = {
			name = "moldavia",
			banner = "moldavia",
			color = {102, 133, 125},
			capital = "moldova"
		},
		Ukraine = {
			name = "ukraine",
			banner = "ukraine",
			color = {61, 111, 133},
			capital = "kiev"
		},
		Poland = {
			name = "poland",
			banner = "poland",
			color = {67, 79, 133},
			capital = "warszawa"
		},
		Lithuania = {
			name = "lithuania",
			banner = "lithuania",
			color = {133, 102, 115},
			capital = "vilnius"
		},
		Latvia = {
			name = "latvia",
			banner = "latvia",
			color = {118, 133, 54},
			capital = "riga"
		},
		Estonia = {
			name = "estonia",
			banner = "estonia",
			color = {44, 48, 133},
			capital = "eesti"
		},
		Belarus = {
			name = "belarus",
			banner = "belarus",
			color = {48, 133, 52},
			capital = "minsk"
		},
		Denmark = {
			name = "denmark",
			banner = "denmark",
			color = {133, 117, 102},
			capital = "denmark"
		},
		Sweden = {
			name = "sweden",
			banner = "sweden",
			color = {122, 107, 133},
			capital = "stockholm"
		},
		Norway = {
			name = "norway",
			banner = "norway",
			color = {133, 81, 52},
			capital = "oslo"
		},
		Finland = {
			name = "finland",
			banner = "finland",
			color = {102, 130, 133},
			capital = "helsinki"
		},
		Russia = {
			name = "russia",
			banner = "russia",
			color = {118, 133, 94},
			capital = "moscow"
		},
		Bulgaria = {
			name = "bulgaria",
			banner = "bulgaria",
			color = {133, 55, 0},
			capital = "sofia"
		},
		Undeveloped_land = {
			name = "undeveloped_land",
			color = {200,200,200},
		}
	},
	provinces = {
		akhisar= {o = "Turkey"},
		albania= {o = "Albania"},
		alesund= {o = "Norway"},
		alta= {o = "Norway"},
		ambrakia= {o = "Greece"},
		amiens= {o = "France"},
		ancona= {o = "Italy"},
		ankara= {o = "Turkey"},
		antalya= {o = "Turkey"},
		arkhangelsk= {o = "Russia"},
		athens= {o = "Greece"},
		badajoz= {o = "Spain"},
		barcelona= {o = "Spain"},
		belgium= {o = "Belgium"},
		beograd= {o = "Serbia"},
		bergen= {o = "Norway"},
		berlin= {o = "Germany"},
		besancon= {o = "France"},
		bialystok= {o = "Poland"},
		bilbo= {o = "Spain"},
		bologna= {o = "Italy"},
		bolu= {o = "Turkey"},
		bordeaux= {o = "France"},
		borlange= {o = "Sweden"},
		bosna_i_hercegovina= {o = "Bosnia_and_herzegovina"},
		bourges= {o = "France"},
		bratislava= {o = "Slovakia"},
		bremen= {o = "Germany"},
		brest= {o = "Belarus"},
		brno= {o = "Czechia"},
		bryansk= {o = "Russia"},
		bucuresti= {o = "Romania"},
		budapest= {o = "Hungary"},
		burgas= {o = "Bulgaria"},
		bursa= {o = "Turkey"},
		bydgoszcz= {o = "Poland"},
		caen= {o = "France"},
		calais= {o = "France"},
		cherkassy= {o = "Ukraine"},
		chernigov= {o = "Ukraine"},
		clermont_ferrand= {o = "France"},
		cluj_napoca= {o = "Romania"},
		coimbra= {o = "Portugal"},
		constanta= {o = "Romania"},
		corum= {o = "Turkey"},
		coruna= {o = "Spain"},
		cosenza= {o = "Italy"},
		crete= {o = "Greece"},
		crimea= {o = "Russia"},
		crna_gora= {o = "Montenegro"},
		cyprus= {o = "Cyprus"},
		daugavpils= {o = "Latvia"},
		denizli= {o = "Turkey"},
		denmark= {o = "Denmark"},
		dijon= {o = "France"},
		dnipro= {o = "Ukraine"},
		donetsk= {o = "Ukraine"},
		dortmund= {o = "Germany"},
		eesti= {o = "Estonia"},
		faro= {o = "Portugal"},
		firenze= {o = "Italy"},
		frankfurt_am_main= {o = "Germany"},
		gabrovo= {o = "Bulgaria"},
		gavle= {o = "Sweden"},
		gdynia= {o = "Poland"},
		gomel= {o = "Belarus"},
		goteborg= {o = "Sweden"},
		graz= {o = "Austria"},
		grodno= {o = "Belarus"},
		gyor= {o = "Hungary"},
		halmstad= {o = "Sweden"},
		hamar= {o = "Norway"},
		hamburg= {o = "Germany"},
		haskovo= {o = "Bulgaria"},
		helsinki= {o = "Finland"},
		iceland= {o = "Iceland"},
		innsbruck= {o = "Austria"},
		isparta= {o = "Turkey"},
		izmir= {o = "Turkey"},
		jonkoping= {o = "Sweden"},
		kalamata= {o = "Greece"},
		kaliningrad= {o = "Russia"},
		kalmar= {o = "Sweden"},
		kaluga= {o = "Russia"},
		karabuk= {o = "Turkey"},
		karaman= {o = "Turkey"},
		karelia= {o = "Russia"},
		karlstad= {o = "Sweden"},
		katrineholm= {o = "Sweden"},
		kharkiv= {o = "Ukraine"},
		kherson= {o = "Ukraine"},
		khmelnitsky= {o = "Ukraine"},
		kielce= {o = "Poland"},
		kiev= {o = "Ukraine"},
		kirov= {o = "Russia"},
		klaipeda= {o = "Lithuania"},
		komi= {o = "Russia"},
		konya= {o = "Turkey"},
		kosice= {o = "Slovakia"},
		kostroma= {o = "Russia"},
		kozan= {o = "Turkey"},
		krakow= {o = "Poland"},
		krasnodar= {o = "Russia"},
		kristiansand= {o = "Norway"},
		kuopio= {o = "Finland"},
		kursk= {o = "Russia"},
		la_rochelle= {o = "France"},
		lasi= {o = "Romania"},
		leeds= {o = "England"},
		limoges= {o = "France"},
		linkoping= {o = "Sweden"},
		lipetsk= {o = "Russia"},
		lisboa= {o = "Portugal"},
		london= {o = "England"},
		lublin= {o = "Poland"},
		lugansk= {o = "Ukraine"},
		lulea= {o = "Sweden"},
		lutsk= {o = "Ukraine"},
		luxembourg= {o = "Luxembourg"},
		lviv= {o = "Ukraine"},
		lyon= {o = "France"},
		macedonia= {o = "Macedonia"},
		madrid= {o = "Spain"},
		magdeburg= {o = "Germany"},
		malmo= {o = "Sweden"},
		marmaris= {o = "Turkey"},
		middle_ireland= {o = "Ireland"},
		milano= {o = "Italy"},
		minsk= {o = "Belarus"},
		mogilev= {o = "Belarus"},
		moldova= {o = "Moldavia"},
		montpellier= {o = "France"},
		moscow= {o = "Russia"},
		munchen= {o = "Germany"},
		murcia= {o = "Spain"},
		murmansk= {o = "Russia"},
		nancy= {o = "France"},
		nantes= {o = "France"},
		napoli= {o = "Italy"},
		nederland= {o = "Netherlands"},
		nenets= {o = "Russia"},
		nice= {o = "France"},
		nigde= {o = "Turkey"},
		nikolaev= {o = "Ukraine"},
		nis= {o = "Serbia"},
		nizhny_novgorod= {o = "Russia"},
		north_africa_1= {p = 0,o = "Undeveloped_land",a = {},lvl = 0},
		north_africa_2= {p = 0,o = "Undeveloped_land",a = {},lvl = 0},
		north_africa_3= {p = 0,o = "Undeveloped_land",a = {},lvl = 0},
		northern_ireland= {o = "England"},
		nottingham= {o = "England"},
		novgorod= {o = "Russia"},
		odessa= {o = "Ukraine"},
		olsztyn= {o = "Poland"},
		orel= {o = "Russia"},
		oslo= {o = "Norway"},
		ostersund= {o = "Sweden"},
		otta= {o = "Norway"},
		oulu= {o = "Finland"},
		paris= {o = "France"},
		penza= {o = "Russia"},
		piter= {o = "Russia"},
		poltava= {o = "Ukraine"},
		porto= {o = "Portugal"},
		poznan= {o = "Poland"},
		praha= {o = "Czechia"},
		pskov= {o = "Russia"},
		reims= {o = "France"},
		rennes= {o = "France"},
		riga= {o = "Latvia"},
		roma= {o = "Italy"},
		rostov_on_don= {o = "Russia"},
		rouen= {o = "France"},
		rovaniemi= {o = "Finland"},
		ryazan= {o = "Russia"},
		samsun= {o = "Turkey"},
		saransk= {o = "Russia"},
		sardegna= {o = "Italy"},
		schweiz= {o = "Switzerland"},
		scotland= {o = "England"},
		sevilla= {o = "Spain"},
		sibiu= {o = "Romania"},
		sicilia= {o = "Italy"},
		sivas= {o = "Turkey"},
		slovenija= {o = "Slovenia"},
		smolensk= {o = "Russia"},
		sofia= {o = "Bulgaria"},
		southern_ireland= {o = "Ireland"},
		stockholm= {o = "Sweden"},
		strasbourg= {o = "France"},
		stuttgart= {o = "Germany"},
		sumy= {o = "Ukraine"},
		sundsvall= {o = "Sweden"},
		szczecin= {o = "Poland"},
		szeged= {o = "Hungary"},
		tambov= {o = "Russia"},
		tampere= {o = "Finland"},
		tekirdag= {o = "Turkey"},
		ternopol= {o = "Ukraine"},
		thessaloniki= {o = "Greece"},
		timisoara= {o = "Romania"},
		torino= {o = "Italy"},
		toulouse= {o = "France"},
		trier= {o = "Germany"},
		trofors= {o = "Norway"},
		tromso= {o = "Norway"},
		trondheim= {o = "Norway"},
		tula= {o = "Russia"},
		tver= {o = "Russia"},
		umea= {o = "Sweden"},
		uzice= {o = "Serbia"},
		valencia= {o = "Spain"},
		valladolid= {o = "Spain"},
		varna= {o = "Bulgaria"},
		vaxjo= {o = "Sweden"},
		venezia= {o = "Italy"},
		vilnius= {o = "Lithuania"},
		vitebsk= {o = "Belarus"},
		vladimir= {o = "Russia"},
		volgograd= {o = "Russia"},
		vologda= {o = "Russia"},
		voronezh= {o = "Russia"},
		vratsa= {o = "Bulgaria"},
		wales= {o = "England"},
		warszawa= {o = "Poland"},
		wien= {o = "Austria"},
		wroclaw= {o = "Poland"},
		yaroslavl= {o = "Russia"},
		zadar= {o = "Croatia"},
		zagreb= {o = "Croatia"},
		zaporozhye= {o = "Ukraine"},
		zaragoza= {o = "Spain"},
		zhitomir= {o = "Ukraine"},
		cheboksary= {o = "Russia"},
	}
}
return game_data