--p - population
--o - own
--a - army
local game_data = {
	id = "wwi",
	map = "europe",
	name = "Первая мировая война(1914)",
	year = 1914,
	technology_lvl = 12,
	player_land = "England",
	lands = {
		England = {
			name = "great_britain",
			banner = "union_jack",
			color = {6, 73, 214},
			capital = "london"
		},
		Spain = {
			name = "spain",
			banner = "spain_civil",
			color = {95, 107, 105},
			capital = "madrid"
		},
		Portugal = {
			name = "portugal",
			banner = "portugal",
			color = {168, 159, 215},
			capital = "lisboa"
		},
		Italy = {
			name = "italy",
			banner = "kingdom_of_italy",
			color = {126, 158, 108},
			capital = "roma",
		},
		Switzerland = {
			name = "switzerland",
			banner = "switzerland",
			color = {209, 207, 102},
			capital = "schweiz",
		},
		France = {
			name = "france",
			banner = "france",
			color = {108, 134, 158},
			capital = "paris",
		},
		Belgium = {
			name = "belgium",
			banner = "belgium",
			color = {215, 170, 159},
			capital = "belgium",
		},
		Netherlands = {
			name = "netherlands",
			banner = "netherlands",
			color = {103, 158, 124},
			capital = "nederland",
		},
		Germany = {
			name = "germany",
			banner = "german_empire",
			color = {65, 104, 107},
			capital = "berlin"
		},
		Luxembourg = {
			name = "luxembourg",
			banner = "luxembourg",
			color = {148, 103, 158},
			capital = "luxembourg"
		},
		Austria_Hungary = {
			name = "austria_hungary",
			banner = "austria_hungary",
			color = {214, 195, 109},
			capital = "budapest"
		},
		Montenegro = {
			name = "montenegro",
			banner = "montenegro",
			color = {158, 116, 103},
			capital = "crna_gora"
		},
		Albania = {
			name = "albania",
			banner = "principality_of_albania_de_facto",
			color = {103, 108, 158},
			capital = "albania"
		},
		Serbia = {
			name = "serbia",
			banner = "serbia",
			color = {96, 166, 209},
			capital = "beograd"
		},
		Greece = {
			name = "greece",
			banner = "greek_on_land",
			color = {120, 153, 82},
			capital = "athens"
		},
		Turkey = {
			name = "ottoman",
			banner = "turkey",
			color = {83, 123, 153},
			capital = "ankara"
		},
		Romania = {
			name = "romania",
			banner = "romania",
			color = {83, 138, 153},
			capital = "bucuresti"
		},
		Denmark = {
			name = "denmark",
			banner = "denmark",
			color = {153, 120, 83},
			capital = "denmark"
		},
		Sweden = {
			name = "sweden",
			banner = "sweden",
			color = {153, 153, 98},
			capital = "stockholm"
		},
		Norway = {
			name = "norway",
			banner = "norway",
			color = {158, 129, 131},
			capital = "oslo"
		},
		Russia = {
			name = "russian_empire",
			banner = "russian_empire",
			color = {98, 153, 111},
			capital = "piter"
		},
		Bulgaria = {
			name = "bulgaria",
			banner = "bulgaria",
			color = {100, 83, 153},
			capital = "sofia"
		},
		Undeveloped_land = {
			name = "undeveloped_land",
			color = {200,200,200},
		}
	},
	provinces = {
		akhisar= {o = "Turkey"},
		albania= {o = "Albania"},
		alesund= {o = "Norway"},
		alta= {o = "Norway"},
		ambrakia= {o = "Greece"},
		amiens= {o = "France"},
		ancona= {o = "Italy"},
		ankara= {o = "Turkey"},
		antalya= {o = "Turkey"},
		arkhangelsk= {o = "Russia"},
		athens= {o = "Greece"},
		badajoz= {o = "Spain"},
		barcelona= {o = "Spain"},
		belgium= {o = "Belgium"},
		beograd= {o = "Serbia"},
		bergen= {o = "Norway"},
		berlin= {o = "Germany"},
		besancon= {o = "France"},
		bialystok= {o = "Russia"},
		bilbo= {o = "Spain"},
		bologna= {o = "Italy"},
		bolu= {o = "Turkey"},
		bordeaux= {o = "France"},
		borlange= {o = "Sweden"},
		bosna_i_hercegovina= {o = "Austria_Hungary"},
		bourges= {o = "France"},
		bratislava= {o = "Austria_Hungary"},
		bremen= {o = "Germany"},
		brest= {o = "Russia"},
		brno= {o = "Austria_Hungary"},
		bryansk= {o = "Russia"},
		bucuresti= {o = "Romania"},
		budapest= {o = "Austria_Hungary"},
		burgas= {o = "Bulgaria"},
		bursa= {o = "Turkey"},
		bydgoszcz= {o = "Germany"},
		caen= {o = "France"},
		calais= {o = "France"},
		cherkassy= {o = "Russia"},
		chernigov= {o = "Russia"},
		clermont_ferrand= {o = "France"},
		cluj_napoca= {o = "Austria_Hungary"},
		coimbra= {o = "Portugal"},
		constanta= {o = "Romania"},
		corum= {o = "Turkey"},
		coruna= {o = "Spain"},
		cosenza= {o = "Italy"},
		crete= {o = "Greece"},
		crimea= {o = "Russia"},
		crna_gora= {o = "Montenegro"},
		cyprus= {o = "England"},
		daugavpils= {o = "Russia"},
		denizli= {o = "Turkey"},
		denmark= {o = "Denmark"},
		dijon= {o = "France"},
		dnipro= {o = "Russia"},
		donetsk= {o = "Russia"},
		dortmund= {o = "Germany"},
		eesti= {o = "Russia"},
		faro= {o = "Portugal"},
		firenze= {o = "Italy"},
		frankfurt_am_main= {o = "Germany"},
		gabrovo= {o = "Bulgaria"},
		gavle= {o = "Sweden"},
		gdynia= {o = "Germany"},
		gomel= {o = "Russia"},
		goteborg= {o = "Sweden"},
		graz= {o = "Austria_Hungary"},
		grodno= {o = "Russia"},
		gyor= {o = "Austria_Hungary"},
		halmstad= {o = "Sweden"},
		hamar= {o = "Norway"},
		hamburg= {o = "Germany"},
		haskovo= {o = "Bulgaria"},
		helsinki= {o = "Russia"},
		iceland= {o = "Denmark"},
		innsbruck= {o = "Austria_Hungary"},
		isparta= {o = "Turkey"},
		izmir= {o = "Turkey"},
		jonkoping= {o = "Sweden"},
		kalamata= {o = "Greece"},
		kaliningrad= {o = "Germany"},
		kalmar= {o = "Sweden"},
		kaluga= {o = "Russia"},
		karabuk= {o = "Turkey"},
		karaman= {o = "Turkey"},
		karelia= {o = "Russia"},
		karlstad= {o = "Sweden"},
		katrineholm= {o = "Sweden"},
		kharkiv= {o = "Russia"},
		kherson= {o = "Russia"},
		khmelnitsky= {o = "Russia"},
		kielce= {o = "Russia"},
		kiev= {o = "Russia"},
		kirov= {o = "Russia"},
		klaipeda= {o = "Russia"},
		komi= {o = "Russia"},
		konya= {o = "Turkey"},
		kosice= {o = "Austria_Hungary"},
		kostroma= {o = "Russia"},
		kozan= {o = "Turkey"},
		krakow= {o = "Austria_Hungary"},
		krasnodar= {o = "Russia"},
		kristiansand= {o = "Norway"},
		kuopio= {o = "Russia"},
		kursk= {o = "Russia"},
		la_rochelle= {o = "France"},
		lasi= {o = "Romania"},
		leeds= {o = "England"},
		limoges= {o = "France"},
		linkoping= {o = "Sweden"},
		lipetsk= {o = "Russia"},
		lisboa= {o = "Portugal"},
		london= {o = "England"},
		lublin= {o = "Russia"},
		lugansk= {o = "Russia"},
		lulea= {o = "Sweden"},
		lutsk= {o = "Russia"},
		luxembourg= {o = "Luxembourg"},
		lviv= {o = "Austria_Hungary"},
		lyon= {o = "France"},
		macedonia= {o = "Serbia"},
		madrid= {o = "Spain"},
		magdeburg= {o = "Germany"},
		malmo= {o = "Sweden"},
		marmaris= {o = "Turkey"},
		middle_ireland= {o = "England"},
		milano= {o = "Italy"},
		minsk= {o = "Russia"},
		mogilev= {o = "Russia"},
		moldova= {o = "Russia"},
		montpellier= {o = "France"},
		moscow= {o = "Russia"},
		munchen= {o = "Germany"},
		murcia= {o = "Spain"},
		murmansk= {o = "Russia"},
		nancy= {o = "France"},
		nantes= {o = "France"},
		napoli= {o = "Italy"},
		nederland= {o = "Netherlands"},
		nenets= {o = "Russia"},
		nice= {o = "France"},
		nigde= {o = "Turkey"},
		nikolaev= {o = "Russia"},
		nis= {o = "Serbia"},
		nizhny_novgorod= {o = "Russia"},
		north_africa_1= {o = "Spain"},
		north_africa_2= {o = "Undeveloped_land"},
		north_africa_3= {o = "Undeveloped_land"},
		northern_ireland= {o = "England"},
		nottingham= {o = "England"},
		novgorod= {o = "Russia"},
		odessa= {o = "Russia"},
		olsztyn= {o = "Germany"},
		orel= {o = "Russia"},
		oslo= {o = "Norway"},
		ostersund= {o = "Sweden"},
		otta= {o = "Norway"},
		oulu= {o = "Russia"},
		paris= {o = "France"},
		penza= {o = "Russia"},
		piter= {o = "Russia"},
		poltava= {o = "Russia"},
		porto= {o = "Portugal"},
		poznan= {o = "Germany"},
		praha= {o = "Austria_Hungary"},
		pskov= {o = "Russia"},
		reims= {o = "France"},
		rennes= {o = "France"},
		riga= {o = "Russia"},
		roma= {o = "Italy"},
		rostov_on_don= {o = "Russia"},
		rouen= {o = "France"},
		rovaniemi= {o = "Russia"},
		ryazan= {o = "Russia"},
		samsun= {o = "Turkey"},
		saransk= {o = "Russia"},
		sardegna= {o = "Italy"},
		schweiz= {o = "Switzerland"},
		scotland= {o = "England"},
		sevilla= {o = "Spain"},
		sibiu= {o = "Austria_Hungary"},
		sicilia= {o = "Italy"},
		sivas= {o = "Turkey"},
		slovenija= {o = "Austria_Hungary"},
		smolensk= {o = "Russia"},
		sofia= {o = "Bulgaria"},
		southern_ireland= {o = "England"},
		stockholm= {o = "Sweden"},
		strasbourg= {o = "Germany"},
		stuttgart= {o = "Germany"},
		sumy= {o = "Russia"},
		sundsvall= {o = "Sweden"},
		szczecin= {o = "Germany"},
		szeged= {o = "Austria_Hungary"},
		tambov= {o = "Russia"},
		tampere= {o = "Russia"},
		tekirdag= {o = "Turkey"},
		ternopol= {o = "Russia"},
		thessaloniki= {o = "Greece"},
		timisoara= {o = "Austria_Hungary"},
		torino= {o = "Italy"},
		toulouse= {o = "France"},
		trier= {o = "Germany"},
		trofors= {o = "Norway"},
		tromso= {o = "Norway"},
		trondheim= {o = "Norway"},
		tula= {o = "Russia"},
		tver= {o = "Russia"},
		umea= {o = "Sweden"},
		uzice= {o = "Serbia"},
		valencia= {o = "Spain"},
		valladolid= {o = "Spain"},
		varna= {o = "Bulgaria"},
		vaxjo= {o = "Sweden"},
		venezia= {o = "Italy"},
		vilnius= {o = "Russia"},
		vitebsk= {o = "Russia"},
		vladimir= {o = "Russia"},
		volgograd= {o = "Russia"},
		vologda= {o = "Russia"},
		voronezh= {o = "Russia"},
		vratsa= {o = "Bulgaria"},
		wales= {o = "England"},
		warszawa= {o = "Russia"},
		wien= {o = "Austria_Hungary"},
		wroclaw= {o = "Germany"},
		yaroslavl= {o = "Russia"},
		zadar= {o = "Austria_Hungary"},
		zagreb= {o = "Austria_Hungary"},
		zaporozhye= {o = "Russia"},
		zaragoza= {o = "Spain"},
		zhitomir= {o = "Russia"},
		cheboksary= {o = "Russia"},
	}
}
return game_data